/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author marti
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        
        PanelSignUp.setVisible(false);
        pageAdminDashboard.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelSignIn = new javax.swing.JPanel();
        PanelSignIn_LabelID = new javax.swing.JLabel();
        PanelSignIn_TextFieldID = new javax.swing.JTextField();
        PanelSignIn_LabelPassword = new javax.swing.JLabel();
        PanelSignIn_PasswordField = new javax.swing.JPasswordField();
        PanelSignIn_ButtonSignIn = new javax.swing.JButton();
        PanelSignIn_ButtonSignUp = new javax.swing.JButton();
        PanelSignIn_LabelPicture = new javax.swing.JLabel();
        PanelSignUp = new javax.swing.JPanel();
        PanelSignUp_LabelID = new javax.swing.JLabel();
        PanelSignUp_TextFieldID = new javax.swing.JTextField();
        PanelSignUp_LabelPassword = new javax.swing.JLabel();
        PanelSignUp_PasswordField = new javax.swing.JPasswordField();
        PanelSignUp_ButtonSignUp = new javax.swing.JButton();
        PanelSignUp_ButtonBack = new javax.swing.JButton();
        PanelSignUp_LabelPicture = new javax.swing.JLabel();
        pageAdminDashboard = new javax.swing.JPanel();
        AdminDropDownUsername = new javax.swing.JPanel();
        LabelSignOutAdmin = new javax.swing.JLabel();
        LabelProfileAdmin = new javax.swing.JLabel();
        AdminlHeader = new javax.swing.JPanel();
        LabelDropDownToggleAdmin = new javax.swing.JLabel();
        AdminlMenu = new javax.swing.JPanel();
        pageViewAdmin = new javax.swing.JPanel();
        ButtonAddAdmin = new javax.swing.JButton();
        ScrollPaneAdmin = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setName("main frame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelSignIn.setBackground(new java.awt.Color(255, 255, 255));
        PanelSignIn.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        PanelSignIn.setMaximumSize(new java.awt.Dimension(1920, 1080));
        PanelSignIn.setMinimumSize(new java.awt.Dimension(1280, 720));
        PanelSignIn.setName("login page"); // NOI18N
        PanelSignIn.setPreferredSize(new java.awt.Dimension(1280, 720));

        PanelSignIn_LabelID.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        PanelSignIn_LabelID.setText("ID");

        PanelSignIn_TextFieldID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PanelSignIn_TextFieldID.setToolTipText("Username");
        PanelSignIn_TextFieldID.setMaximumSize(new java.awt.Dimension(280, 36));
        PanelSignIn_TextFieldID.setMinimumSize(new java.awt.Dimension(280, 36));
        PanelSignIn_TextFieldID.setPreferredSize(new java.awt.Dimension(280, 36));
        PanelSignIn_TextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanelSignIn_TextFieldIDActionPerformed(evt);
            }
        });

        PanelSignIn_LabelPassword.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        PanelSignIn_LabelPassword.setText("Password");

        PanelSignIn_PasswordField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        PanelSignIn_PasswordField.setToolTipText("Password");
        PanelSignIn_PasswordField.setMaximumSize(new java.awt.Dimension(280, 36));
        PanelSignIn_PasswordField.setMinimumSize(new java.awt.Dimension(280, 36));
        PanelSignIn_PasswordField.setPreferredSize(new java.awt.Dimension(280, 36));

        PanelSignIn_ButtonSignIn.setBackground(new java.awt.Color(255, 255, 255));
        PanelSignIn_ButtonSignIn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PanelSignIn_ButtonSignIn.setText("Sign In");
        PanelSignIn_ButtonSignIn.setToolTipText("");
        PanelSignIn_ButtonSignIn.setMaximumSize(new java.awt.Dimension(127, 36));
        PanelSignIn_ButtonSignIn.setMinimumSize(new java.awt.Dimension(127, 36));
        PanelSignIn_ButtonSignIn.setPreferredSize(new java.awt.Dimension(127, 36));
        PanelSignIn_ButtonSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelSignIn_ButtonSignInMouseClicked(evt);
            }
        });

        PanelSignIn_ButtonSignUp.setBackground(new java.awt.Color(34, 125, 194));
        PanelSignIn_ButtonSignUp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PanelSignIn_ButtonSignUp.setForeground(new java.awt.Color(255, 255, 255));
        PanelSignIn_ButtonSignUp.setText("Sign Up");
        PanelSignIn_ButtonSignUp.setToolTipText("");
        PanelSignIn_ButtonSignUp.setMaximumSize(new java.awt.Dimension(127, 36));
        PanelSignIn_ButtonSignUp.setMinimumSize(new java.awt.Dimension(127, 36));
        PanelSignIn_ButtonSignUp.setPreferredSize(new java.awt.Dimension(127, 36));
        PanelSignIn_ButtonSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelSignIn_ButtonSignUpMouseClicked(evt);
            }
        });
        PanelSignIn_ButtonSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanelSignIn_ButtonSignUpActionPerformed(evt);
            }
        });

        PanelSignIn_LabelPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/student.jpg"))); // NOI18N
        PanelSignIn_LabelPicture.setText("jLabel1");

        javax.swing.GroupLayout PanelSignInLayout = new javax.swing.GroupLayout(PanelSignIn);
        PanelSignIn.setLayout(PanelSignInLayout);
        PanelSignInLayout.setHorizontalGroup(
            PanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSignInLayout.createSequentialGroup()
                .addComponent(PanelSignIn_LabelPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addGroup(PanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelSignIn_TextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelSignIn_LabelID)
                    .addComponent(PanelSignIn_LabelPassword)
                    .addGroup(PanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(PanelSignInLayout.createSequentialGroup()
                            .addComponent(PanelSignIn_ButtonSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelSignIn_ButtonSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(PanelSignIn_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(252, 252, 252))
        );
        PanelSignInLayout.setVerticalGroup(
            PanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSignInLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(PanelSignIn_LabelID)
                .addGap(6, 6, 6)
                .addComponent(PanelSignIn_TextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(PanelSignIn_LabelPassword)
                .addGap(6, 6, 6)
                .addComponent(PanelSignIn_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(PanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PanelSignIn_ButtonSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelSignIn_ButtonSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(PanelSignIn_LabelPicture, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        getContentPane().add(PanelSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        PanelSignUp.setBackground(new java.awt.Color(255, 255, 255));
        PanelSignUp.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        PanelSignUp.setMaximumSize(new java.awt.Dimension(1920, 1080));
        PanelSignUp.setMinimumSize(new java.awt.Dimension(1280, 720));
        PanelSignUp.setName("login page"); // NOI18N

        PanelSignUp_LabelID.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        PanelSignUp_LabelID.setText("ID");

        PanelSignUp_TextFieldID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PanelSignUp_TextFieldID.setToolTipText("Username");
        PanelSignUp_TextFieldID.setMaximumSize(new java.awt.Dimension(280, 36));
        PanelSignUp_TextFieldID.setMinimumSize(new java.awt.Dimension(280, 36));
        PanelSignUp_TextFieldID.setPreferredSize(new java.awt.Dimension(280, 36));
        PanelSignUp_TextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanelSignUp_TextFieldIDActionPerformed(evt);
            }
        });

        PanelSignUp_LabelPassword.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        PanelSignUp_LabelPassword.setText("Password");

        PanelSignUp_PasswordField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PanelSignUp_PasswordField.setToolTipText("Password");
        PanelSignUp_PasswordField.setMaximumSize(new java.awt.Dimension(280, 36));
        PanelSignUp_PasswordField.setMinimumSize(new java.awt.Dimension(280, 36));
        PanelSignUp_PasswordField.setPreferredSize(new java.awt.Dimension(280, 36));

        PanelSignUp_ButtonSignUp.setBackground(new java.awt.Color(34, 125, 194));
        PanelSignUp_ButtonSignUp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PanelSignUp_ButtonSignUp.setForeground(new java.awt.Color(255, 255, 255));
        PanelSignUp_ButtonSignUp.setText("Sign Up");
        PanelSignUp_ButtonSignUp.setToolTipText("");
        PanelSignUp_ButtonSignUp.setMaximumSize(new java.awt.Dimension(280, 36));
        PanelSignUp_ButtonSignUp.setMinimumSize(new java.awt.Dimension(280, 36));
        PanelSignUp_ButtonSignUp.setPreferredSize(new java.awt.Dimension(280, 36));

        PanelSignUp_ButtonBack.setBackground(new java.awt.Color(255, 255, 255));
        PanelSignUp_ButtonBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PanelSignUp_ButtonBack.setText("Back");
        PanelSignUp_ButtonBack.setToolTipText("");
        PanelSignUp_ButtonBack.setMaximumSize(new java.awt.Dimension(280, 36));
        PanelSignUp_ButtonBack.setMinimumSize(new java.awt.Dimension(280, 36));
        PanelSignUp_ButtonBack.setPreferredSize(new java.awt.Dimension(280, 36));
        PanelSignUp_ButtonBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelSignUp_ButtonBackMouseClicked(evt);
            }
        });

        PanelSignUp_LabelPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/student2.jpg"))); // NOI18N
        PanelSignUp_LabelPicture.setText("jLabel1");

        javax.swing.GroupLayout PanelSignUpLayout = new javax.swing.GroupLayout(PanelSignUp);
        PanelSignUp.setLayout(PanelSignUpLayout);
        PanelSignUpLayout.setHorizontalGroup(
            PanelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSignUpLayout.createSequentialGroup()
                .addComponent(PanelSignUp_LabelPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addGroup(PanelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelSignUp_ButtonSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelSignUp_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelSignUp_TextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelSignUp_LabelID)
                    .addComponent(PanelSignUp_LabelPassword)
                    .addComponent(PanelSignUp_ButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(252, 252, 252))
        );
        PanelSignUpLayout.setVerticalGroup(
            PanelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSignUpLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(PanelSignUp_LabelID)
                .addGap(6, 6, 6)
                .addComponent(PanelSignUp_TextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(PanelSignUp_LabelPassword)
                .addGap(6, 6, 6)
                .addComponent(PanelSignUp_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(PanelSignUp_ButtonSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(PanelSignUp_ButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSignUpLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelSignUp_LabelPicture))
        );

        getContentPane().add(PanelSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pageAdminDashboard.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pageAdminDashboard.setMaximumSize(new java.awt.Dimension(1920, 1080));
        pageAdminDashboard.setMinimumSize(new java.awt.Dimension(1280, 720));
        pageAdminDashboard.setName("login page"); // NOI18N
        pageAdminDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminDropDownUsername.setBackground(new java.awt.Color(255, 255, 255));
        AdminDropDownUsername.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        AdminDropDownUsername.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelSignOutAdmin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelSignOutAdmin.setText("Sign Out");
        AdminDropDownUsername.add(LabelSignOutAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        LabelProfileAdmin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelProfileAdmin.setText("Profile");
        AdminDropDownUsername.add(LabelProfileAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        pageAdminDashboard.add(AdminDropDownUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 60, 150, 80));

        AdminlHeader.setBackground(new java.awt.Color(255, 255, 255));
        AdminlHeader.setMaximumSize(new java.awt.Dimension(1100, 60));
        AdminlHeader.setMinimumSize(new java.awt.Dimension(1100, 60));
        AdminlHeader.setPreferredSize(new java.awt.Dimension(1100, 60));
        AdminlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelDropDownToggleAdmin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelDropDownToggleAdmin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelDropDownToggleAdmin.setText("Username");
        LabelDropDownToggleAdmin.setMaximumSize(new java.awt.Dimension(150, 30));
        LabelDropDownToggleAdmin.setMinimumSize(new java.awt.Dimension(150, 30));
        LabelDropDownToggleAdmin.setPreferredSize(new java.awt.Dimension(150, 30));
        AdminlHeader.add(LabelDropDownToggleAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, -1, -1));

        pageAdminDashboard.add(AdminlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 1100, -1));

        AdminlMenu.setBackground(new java.awt.Color(34, 125, 194));
        AdminlMenu.setMaximumSize(new java.awt.Dimension(180, 640));
        AdminlMenu.setMinimumSize(new java.awt.Dimension(180, 640));
        AdminlMenu.setPreferredSize(new java.awt.Dimension(180, 640));

        javax.swing.GroupLayout AdminlMenuLayout = new javax.swing.GroupLayout(AdminlMenu);
        AdminlMenu.setLayout(AdminlMenuLayout);
        AdminlMenuLayout.setHorizontalGroup(
            AdminlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        AdminlMenuLayout.setVerticalGroup(
            AdminlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );

        pageAdminDashboard.add(AdminlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 960));

        pageViewAdmin.setBackground(new java.awt.Color(255, 255, 255));
        pageViewAdmin.setMaximumSize(new java.awt.Dimension(1079, 870));
        pageViewAdmin.setMinimumSize(new java.awt.Dimension(1070, 870));

        ButtonAddAdmin.setBackground(new java.awt.Color(255, 255, 255));
        ButtonAddAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonAddAdmin.setText("Add New");
        ButtonAddAdmin.setToolTipText("");
        ButtonAddAdmin.setMaximumSize(new java.awt.Dimension(127, 36));
        ButtonAddAdmin.setMinimumSize(new java.awt.Dimension(127, 36));
        ButtonAddAdmin.setPreferredSize(new java.awt.Dimension(127, 36));
        ButtonAddAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonAddAdminMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pageViewAdminLayout = new javax.swing.GroupLayout(pageViewAdmin);
        pageViewAdmin.setLayout(pageViewAdminLayout);
        pageViewAdminLayout.setHorizontalGroup(
            pageViewAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pageViewAdminLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pageViewAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonAddAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScrollPaneAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        pageViewAdminLayout.setVerticalGroup(
            pageViewAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pageViewAdminLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(ButtonAddAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(ScrollPaneAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pageAdminDashboard.add(pageViewAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 1070, 870));

        getContentPane().add(pageAdminDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PanelSignIn_TextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanelSignIn_TextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelSignIn_TextFieldIDActionPerformed

    private void PanelSignUp_TextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanelSignUp_TextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelSignUp_TextFieldIDActionPerformed

    private void PanelSignIn_ButtonSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanelSignIn_ButtonSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelSignIn_ButtonSignUpActionPerformed

    private void PanelSignIn_ButtonSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelSignIn_ButtonSignUpMouseClicked
        // TODO add your handling code here:
        PanelSignIn.setVisible(false);
        PanelSignUp.setVisible(true);
        pageAdminDashboard.setVisible(false);
    }//GEN-LAST:event_PanelSignIn_ButtonSignUpMouseClicked

    private void PanelSignUp_ButtonBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelSignUp_ButtonBackMouseClicked
        // TODO add your handling code here:
        PanelSignIn.setVisible(true);
        PanelSignUp.setVisible(false);
        pageAdminDashboard.setVisible(false);
    }//GEN-LAST:event_PanelSignUp_ButtonBackMouseClicked

    private void PanelSignIn_ButtonSignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelSignIn_ButtonSignInMouseClicked
        // TODO add your handling code here:
        PanelSignIn.setVisible(false);
        PanelSignUp.setVisible(false);
        pageAdminDashboard.setVisible(true);
    }//GEN-LAST:event_PanelSignIn_ButtonSignInMouseClicked

    private void ButtonAddAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAddAdminMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonAddAdminMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminDropDownUsername;
    private javax.swing.JPanel AdminlHeader;
    private javax.swing.JPanel AdminlMenu;
    private javax.swing.JButton ButtonAddAdmin;
    private javax.swing.JLabel LabelDropDownToggleAdmin;
    private javax.swing.JLabel LabelProfileAdmin;
    private javax.swing.JLabel LabelSignOutAdmin;
    private javax.swing.JPanel PanelSignIn;
    private javax.swing.JButton PanelSignIn_ButtonSignIn;
    private javax.swing.JButton PanelSignIn_ButtonSignUp;
    private javax.swing.JLabel PanelSignIn_LabelID;
    private javax.swing.JLabel PanelSignIn_LabelPassword;
    private javax.swing.JLabel PanelSignIn_LabelPicture;
    private javax.swing.JPasswordField PanelSignIn_PasswordField;
    private javax.swing.JTextField PanelSignIn_TextFieldID;
    private javax.swing.JPanel PanelSignUp;
    private javax.swing.JButton PanelSignUp_ButtonBack;
    private javax.swing.JButton PanelSignUp_ButtonSignUp;
    private javax.swing.JLabel PanelSignUp_LabelID;
    private javax.swing.JLabel PanelSignUp_LabelPassword;
    private javax.swing.JLabel PanelSignUp_LabelPicture;
    private javax.swing.JPasswordField PanelSignUp_PasswordField;
    private javax.swing.JTextField PanelSignUp_TextFieldID;
    private javax.swing.JScrollPane ScrollPaneAdmin;
    private javax.swing.JPanel pageAdminDashboard;
    private javax.swing.JPanel pageViewAdmin;
    // End of variables declaration//GEN-END:variables
}
